//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlegriaEmbotelladaEntities : DbContext
    {
        public AlegriaEmbotelladaEntities()
            : base("name=AlegriaEmbotelladaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tb_Artículo> tb_Artículo { get; set; }
        public virtual DbSet<tb_Consumidor> tb_Consumidor { get; set; }
        public virtual DbSet<tb_Login> tb_Login { get; set; }
        public virtual DbSet<tb_Promoción> tb_Promoción { get; set; }
        public virtual DbSet<tb_Proveedor> tb_Proveedor { get; set; }
        public virtual DbSet<tb_Sucursal> tb_Sucursal { get; set; }
    }
}
