//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Consumidor
    {
        public int PK_Consumidor { get; set; }
        public string Primer_Nombre { get; set; }
        public string Primer_Apellido { get; set; }
        public int edad { get; set; }
        public string email { get; set; }
        public int FK_Usuario { get; set; }
    
        public virtual tb_Login tb_Login { get; set; }
    }
}
