//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Promoción
    {
        public int PK_Promoción { get; set; }
        public string Dia_Inicio { get; set; }
        public string Dia_Finalización { get; set; }
        public int FK_Sucursal { get; set; }
        public int FK_Artículo { get; set; }
        public string Descripción { get; set; }
        public int Cantidad_Artículo { get; set; }
    
        public virtual tb_Artículo tb_Artículo { get; set; }
        public virtual tb_Sucursal tb_Sucursal { get; set; }
    }
}
