//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Sucursal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Sucursal()
        {
            this.tb_Promoción = new HashSet<tb_Promoción>();
        }
    
        public int PK_Sucursal { get; set; }
        public string Nombre_Sucursal { get; set; }
        public string Calle { get; set; }
        public int Número { get; set; }
        public string Colonia { get; set; }
        public int FK_Promoción { get; set; }
        public string Municipio_Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Promoción> tb_Promoción { get; set; }
    }
}
